version: '2.4'

services:
  jar3d_req_module:
    build: .
    ports:
      - "8106:8105"
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
    #   - LLM_SHERPA_SERVER=http://nlm-ingestor:5002/api/parseDocument?renderFormat=all&useNewIndentParser=yes&applyOcr=no&timeout=15
    # depends_on:
    #   - nlm-ingestor_mod
    volumes:
      # - ./config:/app/config
      - ./fastembed_cache:/app/fastembed_cache
      - ./reranker_cache:/app/reranker_cache
      # - ./agent_memory:/agent_memory
    mem_limit: 7.5g
    cpus: 5.0
    networks:
      - jar3d_req_network  # Use custom network

  # nlm-ingestor_mod:
  #   image: ghcr.io/nlmatics/nlm-ingestor:latest
  #   ports:
  #     - "5002:5001"
  #   networks:
  #     - jar3d_network  # Use custom network

networks:
  jar3d_req_network:
    driver: bridge  # Default network driver (bridge)
